language: ruby
install:
  - gem install sinatra
  - gem install cucumber
  - gem install rack-test
  - gem install webrat
  - gem install rspec
  - gem install simplecov
  - gem install simplecov-console

script: bundle exec rake spec